config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :pickups
  put 'pickups/coordinates/:id' => 'pickups#update_coordinates'
  patch 'pickups/coordinates/:id' => 'pickups#update_coordinates'
  resources :users
  
  get 'profile', to: 'users#profile'
  get 'signup', to: 'users#signup_new'
  post 'signup', to: 'users#signup'

  root 'dashboard#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    wallet_id = get_logged_user.wallet.id
    @years = Pickup.pluck('DISTINCT year').sort.reverse
    @year = (params['year'] || @years.max).to_i

    @coins_by_type = ActiveRecord::Base.connection.execute("
      SELECT c.value AS coin, c.short_name AS currency, count(c.id) AS amount
      FROM pickups p
      JOIN coins c ON p.coin_id = c.id
      JOIN users u ON p.picker_id = u.id
      WHERE u.wallet_id = #{wallet_id} AND p.year = #{@year}
      GROUP BY c.id
      ORDER BY c.currency_id, c.value ASC
    ")

    @top_users = ActiveRecord::Base.connection.execute("
      SELECT u.id, u.username, count(u.id) AS coins , sum(c.value) AS value
      FROM users u
      JOIN pickups p ON p.picker_id = u.id
      JOIN coins c ON p.coin_id = c.id
      WHERE u.wallet_id = #{wallet_id} AND p.year = #{@year}
      GROUP BY u.id
      ORDER BY coins DESC
    ")

    all = Pickup.where(wallet_id: wallet_id)
    @pickups_with_location = all.where(year: @year).select { |p| p.has_coordinates? }
    @lat_center = @pickups_with_location.map { |p| p.latitude }.sum(0.0) / @pickups_with_location.length
    @lon_center = @pickups_with_location.map { |p| p.longitude }.sum(0.0) / @pickups_with_location.length
    @users = @top_users.map { |u| u['username']}
    @pickups_by_month = monthly_pickups all
    # by user too

    # Three last pickups
    now = Time.zone.now
    @last_pickups = Pickup.where(wallet_id: wallet_id, picked_at: (15.days.ago.to_date)..(now)).order(picked_at: :desc).limit(3)
  end

  private
    def monthly_pickups all
      pickups_by_month = {}
      pickups_by_month_raw = all.where(year: @year).group_by { |p| "#{p.picker.username}-#{p.picked_at.month}" }
      pickups_by_month_raw.each do |k, v|
        user, month = k.split "-"
        pickups_by_month[user] = {} unless pickups_by_month[user]
        pickups_by_month[user][month] = v.size
      end
      pickups_by_month
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h1><%= @year %> Stats</h1>

<div class="row">
  <div class="col-sm-12 col-xs-12">
    <h2>Last pickups</h2>
    <table class="table">
    <% @last_pickups.each do |pickup| %>
      <tr>
        <td><%= link_to pickup.coin, pickup_path(pickup) %> by <strong><%= pickup.picker.username %></strong>, <%= time_ago_in_words(pickup.picked_at) %> ago.</td>
      </tr>
    <% end %>
    <% if @last_pickups.empty? %>
      <tr><td>There isn't recent pickups. Go out and pick up some coins!</td><tr>
    <% end %>
    </table>
    <%= link_to controller: 'pickups' do %><i class="fa fa-money"></i> See all<% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-xs-12">
    <h2>Top Pickers</h2>
    <table class="table">
    <% @top_users.each_with_index do |top_user, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><strong><%= link_to top_user['username'], user_path(top_user['id']) %></strong></td>
        <td style="text-align: right;"><%= top_user['coins'] %></td>
        <td style="text-align: right;"><%= top_user['value'] %></td>
      </tr>
    <% end %>
    </table>
  </div>

  <div class="col-sm-6 col-xs-12">
    <h2>Coins</h2>
    <table class="table">
      <% @coins_by_type.each_with_index do |coin, index| %>
      <tr>
        <td><%= coin['coin'] %> <%= coin['currency'] %></td>
        <td style="text-align: right;"><%= coin['amount'] %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <h2>Monthly Pickups</h2>
    <div id="monthly-chart" style="height: 300px;"></div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <h2>Coin Map</h2>
    <div id="map-canvas" style="height: 300px; width: 100%;"></div>
  </div>
</div>

<nav style="float: right; margin-top: 24px;">
  <ul class="pagination">
    <% @years.each do |y| %>
    <% if y == @year %>
    <li class="active">
    <% else %>
    <li>
    <% end %>
      <%= link_to y, :year => y %>
    </li>
    <% end %>
  </ul>
</nav>


<script type="text/javascript">
  $(document).ready(function() {
    // Map
    var coins = [
      <% @pickups_with_location.each { |c| %>
        {lat:<%= c.latitude %>, lon:<%= c.longitude %>},
      <% } %>
    ];

/*
    var bounds = new google.maps.LatLngBounds();
    var map = new google.maps.Map(document.getElementById('map-canvas'), {
      mapTypeId: 'roadmap', 
      disableDefaultUI: true,
      zoomControl: true
    });

    for (var i = 0; i < coins.length; i++) {
      var marker = new google.maps.Marker({
          position: new google.maps.LatLng(coins[i].lat, coins[i].lon),
          map: map
      });
      bounds.extend(marker.position);
    }
    map.fitBounds(bounds);
*/

  // https://openlayers.org/en/latest/examples/icon-color.html
  var coinMarkers = coins.map( it => {
    var marker = new ol.Feature({
      geometry: new ol.geom.Point(ol.proj.fromLonLat([it.lon, it.lat]))
    });
    
    marker.setStyle(
      new ol.style.Style({
        image: new ol.style.Icon({
          color: '#c3886a',
          crossOrigin: 'anonymous',
          // For Internet Explorer 11
          imgSize: [20, 20],
          src: '<%= asset_path("dot.svg") %>',
        }),
      })
    );
    return marker;
  });

  var vectorSource = new ol.source.Vector({features: coinMarkers});
  var vectorLayer = new ol.layer.Vector({source: vectorSource});

  var map = new ol.Map({
    target: document.getElementById('map-canvas'),
    layers: [
      new ol.layer.Tile({
        source: new ol.source.OSM()
      }), 
      vectorLayer
    ],
    view: new ol.View({
      center: ol.proj.fromLonLat([<%= @lon_center %>, <%= @lat_center %>]),
      zoom: 12
    })
  });
    
    // Monthly chart
    c3.generate({
      bindto: '#monthly-chart',
      data: {
        x: 'x',
        columns: [
          ['x', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'a'],
          <% @users.each do |u| %>
          ['<%= u %>', <% (1..12).each do |m| %><%= @pickups_by_month[u][m.to_s] || 0 %>, <% end %>],
          <% end %>
        ],
        type: 'bar',
        groups: [
          [<%= raw @users.map {|u| "\"#{u}\""}.join "," %>]
        ]
      },
      axis: {
        x: {
          type: 'category' // this needed to load string x value
        }
      }
    });
  });
</script>