config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :pickups
  put 'pickups/coordinates/:id' => 'pickups#update_coordinates'
  patch 'pickups/coordinates/:id' => 'pickups#update_coordinates'
  resources :users
  
  get 'profile', to: 'users#profile'
  get 'signup', to: 'users#signup_new'
  post 'signup', to: 'users#signup'

  root 'dashboard#index'

end

app/models/pickup.rb
require 'csv'

class Pickup < ApplicationRecord
  include Filterable

	validates :picked_at, :picker, :coin, presence: true
  validates :longitude, numericality: { greater_than: -180, less_than: 180 }, allow_nil: true
  validates :latitude, numericality: { greater_than: -90, less_than: 90 }, allow_nil: true
  validate :location_complete?, :wallet_owner

	belongs_to :wallet
  belongs_to :coin
  belongs_to :picker, class_name: "User"

  date_time_attribute :picked_at

  SUPPORTED_FILTERS = [:wallet_id, :year, :picker_id, :has_coords, :has_not_coords]
#  scope :coin, -> (coin_id) { where coin: coin_id }

 # It only works in Postgres
  scope :wallet_id, -> (wallet) {where "wallet_id = ?", wallet}
  scope :year, -> (year)  {where "EXTRACT(YEAR FROM picked_at) = ?", year }
  scope :picker_id, -> (id) { where picker_id: id }
#  scope :handed_over, -> (handed_over) { where handed_over: ActiveRecord::ConnectionAdapters::Column.value_to_boolean(handed_over) }
  scope :has_coords , -> (w) { where "latitude is not null"}
  scope :has_not_coords , -> (w) { where "latitude is null"}

  def has_coordinates?
    not latitude.nil? and not longitude.nil?
  end

  def location_complete?
    if latitude.nil? ^ longitude.nil?
      errors.add(:latitude, "Location is incomplete")
    end
  end

  def wallet_owner
    if wallet != picker.wallet
      errors.add(:wallet, "Picker's wallet incorrect")
    end
  end

  def self.csv_header
    ["Picked at", "Coin", "Picker", "Longitude", "Latitude", "Location", "Comments"]
  end

  def to_csv
    [picked_at, coin.value, picker.username, longitude, latitude, location, comments]
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << csv_header
      all.each do |p|
        csv << p.to_csv
      end
    end
  end

  def self.filter(attributes)
    attributes.permit(SUPPORTED_FILTERS).to_hash.reduce(all) do |scope, (key, value)|
      value.present? ? scope.send(key, value): scope
    end
  end
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  before_action :set_pickup, only: [:show, :edit, :update, :update_coordinates, :destroy]
  helper_method :can_edit

  # GET /pickups
  # GET /pickups.json
  def index
    wallet_id = get_logged_user.wallet.id
    params['wallet_id'] = wallet_id
    @pickers = wallet_pickers

    if params['coordinates'] == 'true'
      params[:has_coords] = true
      params[:has_not_coords] = nil
    elsif params['coordinates'] == 'false'
      params[:has_not_coords] = true
      params[:has_coords] = nil
    end

    @pickups = Pickup
      #.where(wallet_id: wallet_id)
      .filter(params)
      .order(picked_at: :desc)
      .page(params[:page])
      .per(20)

    @show_filter_form = (!(params[:year].blank?)) | (!(params[:picker_id].blank?)) | (!(params[:coordinates].blank?))
    @years = Pickup.pluck('DISTINCT year').sort.reverse
    @year = (params['year'] || @years.max).to_i

    respond_to do |format|
      format.html
      format.csv { render text: @pickups.to_csv }
    end
  end

  # GET /pickups/1
  # GET /pickups/1.json
  def show
    user = get_logged_user
    @can_edit = (user.owner? or @pickup.picker == user)
  end

  # GET /pickups/new
  def new
    @pickup = Pickup.new
    @pickup.picked_at = Time.zone.now
    @pickers = wallet_pickers
    @can_view_hand_over = false
  end

  # GET /pickups/1/edit
  def edit
    @pickers = wallet_pickers
    @edit_mode = true
    user = get_logged_user
    @can_view_hand_over = user.owner?
    @cannot_edit_hand_over = @pickup.picker.id == user.id
  end

  # POST /pickups
  # POST /pickups.json
  def create
    @pickup = Pickup.new(pickup_params)
    @pickup.picker = get_logged_user
    @pickup.wallet = @pickup.picker.wallet
    @pickup.handed_over = @pickup.picker.owner?
    @pickup.year = @pickup.picked_at.year

    respond_to do |format|
      if @pickup.save
        format.html { redirect_to pickups_url, notice: 'Pickup was created.' }
        format.json { render :index, status: :created, location: @pickups }
      else
        format.html { render :new }
        format.json { render json: @pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pickups/1
  # PATCH/PUT /pickups/1.json
  def update
    @pickup.year = @pickup.picked_at.year
    respond_to do |format|
      if @pickup.update(pickup_params)
        format.html { redirect_to pickups_url, notice: 'Pickup was updated.' }
        format.json { render :index, status: :ok, location: @pickups }
      else
        format.html { render :edit }
        format.json { render json: @pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pickups/coordinates/1
  # PATCH/PUT /pickups/coordinates/1.json
  def update_coordinates
    respond_to do |format|
      if @pickup.update(pickup_params)
        format.html { redirect_to pickup_url(@pickup), notice: 'Pickup coordinates were updated.' }
        format.json { render :index, status: :ok, location: @pickups }
      else
        format.html { render :edit }
        format.json { render json: @pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pickups/1
  # DELETE /pickups/1.json
  def destroy
    @pickup.destroy
    respond_to do |format|
      format.html { redirect_to pickups_url, notice: 'Pickup was destroyed.' }
      format.json { head :no_content }
    end
  end

  # Helper
  def can_edit(user_id)
    user = get_logged_user
    user.owner? or user.id == user_id
  end

  private
    def wallet_pickers
      wallet_id = get_logged_user.wallet.id
      User.where(active: true, wallet_id: wallet_id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_pickup
      @pickup = Pickup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pickup_params
      params.require(:pickup).permit(:coin_id, :picked_at_date, :picked_at_time, :comments, :longitude, :latitude,  :location)
    end

    def pickup_coordinates_params
      params.require(:pickup).permit(:longitude, :latitude, :location)
    end
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/views/pickups/_form.html.erb
<%= form_for(@pickup, :html => {:role => 'form'}) do |f| %>
  <% if @pickup.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
      <% @pickup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :coin %><br>
    <%= f.collection_select :coin_id, Coin.all.order(currency_id: :asc, value: :asc), :id, :to_s, {}, {:class => 'form-control'} %>
  </div>

  <%= f.hidden_field :longitude, :class => 'form-control' %>
  <%= f.hidden_field :latitude, :class => 'form-control' %>


  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, :class => 'form-control' %>
  </div>


    <% unless @edit_mode %>
    <div class="pull-right form-group form-inline">
      <a id="show-advanced" data-toggle="collapse" href="#collapseOne"><i class="fa fa-angle-double-right"></i> Show advanced options</a>
      <a id="hide-advanced" data-toggle="collapse" href="#collapseOne" style="display: none;"><i class="fa fa-angle-double-down"></i> Hide advanced options</a>
    </div>
    <div class="clearfix"></div>
    <% end %>

    <div id="collapseOne" <% unless @edit_mode %>class="collapse"<% end %>>
        <div class="form-group">
          <%= f.label :comments %><br>
          <%= f.text_area :comments, rows: 3, class: 'form-control' %>
        </div>
      <div class="row">
        <div class="col-md-4 col-sm-12 form-group">
          <%= f.label :picker %><br>
          <%= f.collection_select :picker_id, @pickers, :id, :username, {}, {:class => 'form-control'} %>
        </div>

        <div class="col-md-4 col-sm-6 form-group">
          <%= f.label 'Date' %><br>
          <%= f.date_field :picked_at_date, :class => 'form-control' %>
        </div>

        <div class="col-md-4 col-sm-6 form-group">
          <%= f.label 'Time' %><br>
          <%= f.time_field :picked_at_time, :value => (@pickup.picked_at_time.strftime("%H:%M")), :class => 'form-control', title: 'Format: hh:mm' %>
        </div>
      </div>
    </div>

  <hr>

  <div class="form-group">
    <% if @edit_mode %>
    <%= f.submit :class => 'btn btn-primary col-xs-12' %>
    <%= link_to 'Cancel', pickups_path, :class => 'btn btn-link' %>
    <% else %>
    <%= f.submit :class => 'btn btn-primary btn-lg col-xs-12' %>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">

  function isDateControlSupported() {
    var tester = document.createElement('input');
    tester.type = 'date';
    tester.value = ':(';
    return tester.type === 'date' && tester.value === '';
  }

  function searchLocationText(lat, lng) {
    // TODO search for text location
  }

  $(document).ready(function() {
    var show_advanced = $('#show-advanced');
    var hide_advanced = $('#hide-advanced');
    var toggle_advanced = function() {
      show_advanced.toggle();
      hide_advanced.toggle();
    }
    show_advanced.click(toggle_advanced);
    hide_advanced.click(toggle_advanced);
  });

  $(document).ready(function() {
    var input = document.getElementById('pickup_location');
    // TODO init search location
  });
</script>

app/views/pickups/edit.html.erb
<h1>Edit pickup</h1>

<%= render 'form' %>


<script>

$(document).ready(function() {
  // Date
  if (!isDateControlSupported()) {
    $('#pickup_picked_at_date').datepicker({format: 'dd/mm/yyyy', weekStart: 1});
  }
});
</script>

app/views/pickups/index.html.erb
<h1>Pickups</h1>

<% if notice %>
<p id="notice" class="text-info"><i class="fa fa-info"></i> <%= notice %></p>
<% end %>

<p>
  <%= link_to new_pickup_path do %><i class="fa fa-plus"></i> New pickup<% end %>
  <span style="padding-right: 1rem;"></span>
  <%= link_to pickups_path(format: "csv"), title: "Download list as a CSV file" do %><i class="fa fa-download"></i> Download<% end %>
</p>

<div class="form-group form-inline">
  <a id="show-filtering" data-toggle="collapse" href="#collapseOne" title="Show filtering options"><i class="fa fa-angle-double-right"></i> Filter</a>
  <a id="hide-filtering" data-toggle="collapse" href="#collapseOne" title="Hide filtering options" style="display: none;"><i class="fa fa-angle-double-down"></i> Hide</a>
</div>
<div id="collapseOne" class="panel panel-default collapse <% if @show_filter_form %>in<% end %>">
  <div class="panel-body">
    <%= form_tag pickups_path, :method => 'get', :role => 'form' do %>
      <div class="row">
        <div class="form-group col-sm-4 col-xs-12">
          <%= label_tag :year %>
          <%= select_tag :year, options_for_select(@years, params[:year]), {include_blank: 'Any year', class: 'form-control'} %>
        </div>
        <div class="form-group col-sm-4 col-xs-12">
          <%= label_tag :picker_id %>
          <%= select_tag :picker_id, options_from_collection_for_select(@pickers, :id, :username, params[:picker_id]), {include_blank: 'Any picker', class: 'form-control'} %>
        </div>
        <!-- TODO -->
        <div class="form-group col-sm-4 col-xs-12">
          <%= label_tag :coordinates %>
          <%= select_tag :coordinates, options_for_select({'Yes' => true, 'No' => false}, params[:coordinates]), {include_blank: 'Whatever', class: 'form-control'} %>
        </div>
      </div>
      <div class="form-group">
        <%= button_tag :name => nil, :class => 'btn' do %><i class="fa fa-search"></i> Filter<% end %>
      </div>
    <% end %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Coin</th>
      <th>Picker</th>
      <th class="hidden-xs">Location</th>
      <th class="hidden-xs"></th>
    </tr>
  </thead>

  <tbody>
    <% @pickups.each do |pickup| %>
      <tr>
        <td><%= pickup.picked_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= link_to pickup.coin, pickup_path(pickup) %></td>
        <td><%= pickup.picker.username %></td>
        <td class="hidden-xs"><span title="<%= pickup.location %>"><%= truncate(pickup.location, length: 24) %></span></td>
        <td class="hidden-xs" style="text-align: right;">
          <div class="btn-group">
            <% if can_edit pickup.picker_id %>
            <%= link_to pickup, method: :delete, data: { confirm: "Do you really want to delete the pickup?" }, :title => "Delete", :class => 'btn btn-default btn-sm' do %><i class="fa fa-trash-o"></i><% end %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= paginate @pickups %></p>

<script type="text/javascript">
  // decide based on params presence
  // TODO use bootstrap caret
  $(document).ready(function() {
    var show_filtering = $('#show-filtering');
    var hide_filtering = $('#hide-filtering');
    var toggle_filtering = function() {
      show_filtering.toggle();
      hide_filtering.toggle();
    }
    show_filtering.click(toggle_filtering);
    hide_filtering.click(toggle_filtering);

    <% if @show_filter_form %>
    show_filtering.hide();
    hide_filtering.show();
    <% else %>
    show_filtering.show();
    hide_filtering.hide();
    <% end %>
  });
</script>

app/views/pickups/new.html.erb
<h1>New pickup</h1>

<%= render 'form' %>

<script>
var POSITION_TIMEOUT = 4000;

function onLocationFound(position) {
  console.debug("Coordinates found: " + position.coords.latitude + ", " + position.coords.longitude);

  $("#pickup_latitude").val(position.coords.latitude);
  $("#pickup_longitude").val(position.coords.longitude);
  //searchLocationText(position.coords.latitude, position.coords.longitude);
}

function handle_error(err) {
  console.warn("Location not found: " + err);
  if ($("#pickup_latitude").val() && $("#pickup_longitude").val()) {
    return;
  }

  if (err.code == 3) {
    navigator.geolocation.getCurrentPosition(onLocationFound, handle_error, {timeout: POSITION_TIMEOUT, enableHighAccuracy: false});
  }
}

// Init
$(document).ready(function() {
  // Adds datepicker if there isn't native control
  if (!isDateControlSupported()) {
    $('#pickup_picked_at_date').datepicker({format: 'dd/mm/yyyy', weekStart: 1});
  }

  // Search location 
  navigator.geolocation.getCurrentPosition(onLocationFound, handle_error, {timeout: POSITION_TIMEOUT, enableHighAccuracy: true});
});
</script>

app/views/pickups/show.html.erb
<h1><%= @pickup.coin %></h1>

<% if notice %>
<p id="notice" class="text-info"><i class="fa fa-info"></i> <%= notice %></p>
<% end %>

<div class="row">
  <div class="col-md-12">
    <p class="lead">Picked by <strong><%= @pickup.picker.username %></strong> on <%= @pickup.picked_at.strftime("%d %B %Y") %> at <%= @pickup.picked_at.strftime("%H:%M") %>.</p>

    <% unless @pickup.comments.blank? %>
    <blockquote>
      <p><%= @pickup.comments %></p>
    </blockquote>
    <% end %>

    <% if @can_edit %>
    <%= link_to edit_pickup_path(@pickup) do %><i class="fa fa-edit"></i> Edit<% end %>
    <% end %>
  </div>

  <div class="col-md-12">
    <h3><% if @pickup.has_coordinates? %><i class="fa fa-location-arrow"></i> <% end %>Location</h3>
    <div id="map-canvas" style="height: 300px;"></div>

    <input id="pac-input" type="text" style="width: 100%;" value="<%= @pickup.location %>"
      <% if @pickup.has_coordinates? %> disabled<% else %> placeholder="Enter location"<% end %>>
    <%= form_for(@pickup, :url =>  {:action => 'update_coordinates'}, :html => {:role => 'form'}) do |f| %>
      <%= f.hidden_field :longitude %>
      <%= f.hidden_field :latitude %>
      <%= f.hidden_field :location %>
      <%= f.button :type => 'submit', :class => 'btn btn-default hidden', :id => "saveCoordinatesBtn" do %>
        <i class="fa fa-save"> Save coordinates</i>
      <% end %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
  let lonLat = [<%= @pickup.longitude %>, <%= @pickup.latitude %>];

<% if @pickup.has_coordinates? %>
  var marker = new ol.Feature({
      geometry: new ol.geom.Point(ol.proj.fromLonLat(lonLat))
  });
  marker.setStyle(
    new ol.style.Style({
      image: new ol.style.Icon({
        color: '#c3886a',
        crossOrigin: 'anonymous',
        // For Internet Explorer 11
        imgSize: [20, 20],
        src: '<%= asset_path("dot.svg") %>',
      }),
    })
  );

  var vectorSource = new ol.source.Vector({features: [marker]});
  var vectorLayer = new ol.layer.Vector({source: vectorSource});

  var map = new ol.Map({
    target: document.getElementById('map-canvas'),
    layers: [
      new ol.layer.Tile({
        source: new ol.source.OSM()
      }), 
      vectorLayer
    ],
    view: new ol.View({
      center: ol.proj.fromLonLat(lonLat),
      zoom: 7
    })
  });
 <% else %>
    // TODO no coordinates case
<% end %>
});
</script>