config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :pickups
  put 'pickups/coordinates/:id' => 'pickups#update_coordinates'
  patch 'pickups/coordinates/:id' => 'pickups#update_coordinates'
  resources :users
  
  get 'profile', to: 'users#profile'
  get 'signup', to: 'users#signup_new'
  post 'signup', to: 'users#signup'

  root 'dashboard#index'

end

app/models/user.rb
class User < ApplicationRecord
  ROLE_OWNER = 1
  ROLE_CONTRIBUTOR = 2
  
  validates :email, presence: true
  validates :username, :email, uniqueness: true, :allow_nil => true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :active, inclusion: { in: [true, false] }
  validate :active_user

  has_secure_password

  belongs_to :wallet, inverse_of: :contributors

  attr_accessor :remember_token

  def active_user
    if active and username.nil?
      errors.add(:username, "Active users must have an username")
    end
  end

  def owner?
    return role == ROLE_OWNER
  end

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    begin
      auth = BCrypt::Password.new(remember_digest).is_password?(remember_token)
      auth
    rescue BCrypt::Errors::InvalidHash
      puts ">>> Invalid token: #{remember_token}"
      false
    end
  end

    # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorise, only: [:signup_new, :signup]

  # GET /users
  # GET /users.json
  def index
    # Finds only current wallet contributors
    wallet_id = get_logged_user.wallet.id
    @users = User.where(wallet_id: wallet_id, role: User::ROLE_CONTRIBUTOR, active: true)
    @invitations = User.where(wallet_id: wallet_id, role: User::ROLE_CONTRIBUTOR, active: false)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @current_user = @user.id == session[:user_id]

    profile_queries
  end

  def profile
    @user = User.find(session[:user_id])
    @current_user = true
    profile_queries
    
    render "show"
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.active = false
    @user.role = User::ROLE_CONTRIBUTOR
    @user.wallet_id = get_logged_user.wallet.id
    @user.password = SecureRandom.hex(16)

    respond_to do |format|
      if @user.save
        owner = User.find(session[:user_id])
        InvitationNotifier.invite(owner, @user).deliver

        format.html { redirect_to users_path, notice: "An invitation was sent to #{@user.email}" }
        format.json { render :show, status: :created, location: users_path }
      else
        format.html { render :new }

        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    # TODO: Only the current user can update theirself
    update_type = params[:user][:update_type]
    params[:user].delete(:update_type)

    puts update_type
    puts params[:user][:username]
    puts params[:user][:password]

    if update_type == "username" and params[:user][:username].blank?
      @user.errors[:username] << "can't be empty"
      render :edit
    elsif update_type == "password" and params[:user][:password].empty?
      @user.errors[:password] << "can't be empty"
      render :edit
    else
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    # TODO An contributor can't delete other users
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /signup
  def signup_new
    # TODO only owner
    @error = true

    if session[:user_id]
      respond_to do |format|
        format.html { redirect_to dashboard_path , notice: 'You should first log out.' }
      end
    end

    if params[:u] and params[:p]
      @user = User.find_by(email: params[:u], active: false, password_digest: URI.decode(params[:p]))
      if @user
        @error = false
      end
    end

    if @error
      respond_to do |format|
        format.html { redirect_to :login, alert: 'Something wrong happened.' }
      end
    else
      @login_page = true
      respond_to do |format|
        format.html { render :signup_new, layout: 'public' }
      end
    end
  end

  # POST /signup
  def signup
    # Only owner
    @user = User.find_by(email: params[:email])
    @user.active = true
    respond_to do |format|
      if @user.update(params.permit(:username, :password, :password_confirmation))
        format.html { redirect_to login_path, notice: 'Your user has been confirmed. Please sign in.' }
      else
        @login_page = true
        format.html { render :signup_new, layout: 'public', email: params[:email]  }
      end
    end
  end


  private
    def profile_queries
      @coins = Pickup.where(picker_id: @user.id).count
      @money = Pickup.where(picker_id: @user.id).joins(:coin).sum(:value)
      @last_pickups = Pickup.where(picker_id: @user.id).order(picked_at: :desc).limit(3)

      wallet_id = get_logged_user.wallet.id
      @years = Pickup.pluck('DISTINCT year').sort.reverse
      @year = (params['year'] || @years.max).to_i
      @top_users = ActiveRecord::Base.connection.execute("
        SELECT u.id, u.username, count(u.id) AS coins , sum(c.value) AS value
        FROM users u
        JOIN pickups p ON p.picker_id = u.id
        JOIN coins c ON p.coin_id = c.id
        WHERE u.wallet_id = #{wallet_id} AND p.year = #{@year}
        GROUP BY u.id
        ORDER BY coins DESC
      ")
      all = Pickup.where(wallet_id: wallet_id)
      @pickups_by_year = year_pickups all #all.group(:year).count
      @users = @top_users.map { |u| u['username']}
    end

    def year_pickups all
      pickups_by_year = {}
      pickups_by_year_raw = all.group_by { |p| "#{p.picker.username}-#{p.year}" }
      pickups_by_year_raw.each do |k, v|
        user, year = k.split "-"
        pickups_by_year[user] = {} unless pickups_by_year[user]
        pickups_by_year[user][year] = v.size
      end
      pickups_by_year
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit user</h1>

<% if @user.errors.any? %>
  <div id="password_error_explanation" class="alert alert-danger">
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@user, :html => {:role => 'form'}) do |f| %>
  <div class="form-group">
    <%= f.label :username %><br/>
    <%= f.text_field :username, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit 'Save username', class: 'btn btn-primary'%>
  </div>
  <%= f.hidden_field :update_type, value: "username" %>
<% end %>
<hr/>


<%= form_for(@user, :html => {:role => 'form'}) do |f| %>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit 'Change password', class: 'btn btn-primary'%>
  </div>
  <%= f.hidden_field :update_type, value: "password" %>
<% end %>
</div>

app/views/users/index.html.erb
<h1>Contributors</h1>

<% if notice %>
<p id="notice" class="text-info"><i class="fa fa-info"></i> <%= notice %></p>
<% end %>

<p><%= link_to new_user_path do %> <i class="fa fa-plus"></i> New contributor <% end %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td style="text-align: right;">
          <div class="btn-group">
            <%= link_to user, :title => "Show", :class => 'btn btn-default btn-sm' do %><i class="fa fa-eye"></i><% end %>
            <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete the contributor #{user.username}?" }, :title => "Delete", :class => 'btn btn-default btn-sm' do %><i class="fa fa-trash-o"></i><% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Invitations</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Sent on</th>
      <th>To</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |user| %>
      <tr>
        <td><%= user.created_at.strftime("%m/%d/%Y %H:%M") %></td>
        <td><%= user.email %></td>
        <td style="text-align: right;">
          <div class="btn-group">
            <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete the invitation to #{user.email}?" }, :title => "Delete", :class => 'btn btn-default btn-sm' do %><i class="fa fa-trash-o"></i><% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New contributor</h1>

<p class="text-info"><i class="fa fa-info"></i> An email with the new contributors's password will be sent to the address provided.</p>

<%= form_for(@user, :html => {:role => 'form'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Contributor's email" %><br>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <hr/>

  <div class="form-group actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<div>
<% if notice %>
  <p id="notice" class="text-info"><i class="fa fa-info"></i> <%= notice %></p>
<% end %>
<div>

<div class="row">
  <div class="col-md-12 col-xs-12">
    <h1><%= @user.username %></h1>
    <p><%= @user.email %></p>

    <% if @current_user %><%= link_to edit_user_path(@user) do %> <i class="fa fa-edit"></i> Edit<% end %><% end %>
    <% if owner? %><%= link_to controller: 'users' do %> | <i class=" fa fa-users"></i> Contributors<% end %><% end %>
    <% if @current_user %><%= link_to logout_path, method: :delete  do %> | <i class="fa fa-sign-out"></i> Log out<% end %><% end %>
  </div>

  <div class="col-sm-6 col-xs-12">
    <h2>Last pickups</h2>
    <table class="table">
    <% @last_pickups.each do |pickup| %>
      <tr>
        <td><%= link_to pickup.coin, pickup_path(pickup) %>, <%= time_ago_in_words(pickup.picked_at) %> ago.</td>
      </tr>
    <% end %>
    <% if @last_pickups.empty? %>
      <tr><td>No pickups yet. Try harder!</td><tr>
    <% end %>
    </table>
    <%= link_to controller: 'pickups', picker_id: @user.id, year: @year do %><i class="fa fa-money"></i> See all<% end %>
  </div>
</div>

<h2>Stats</h2>
<div class="row">
  <div class="col-sm-6 col-xs-6">
    <div id="first-well" class="well" >
      <h2><strong><%= @coins %></strong></h2>
      <p class="lead">Coins</p>
    </div>
  </div>

  <div class="col-sm-6 col-xs-6">
    <div class="well">
      <h2><strong><%= @money %></strong></h2>
      <p class="lead">Cents</p>
    </div>
  </div>

  <div class="col-sm-12">
    <h3>Coins by Year</h3>
    <div id="year-chart" style="height: 300px;"></div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    // Year chart
    c3.generate({
      bindto: '#year-chart',
      data: {
        x: 'x',
        columns: [
          ['x', <%= raw @years.reverse.map { |y| "'#{y}'"}.join(",") %> ],
          <% @users.each do |u| %>
            ['<%= u %>', <% @years.reverse.each do |y| %><%= @pickups_by_year[u][y.to_s] || 0 %>, <% end %>],
          <% end %>
        ],
        types: {
          <%= raw @users.map {|u| "#{u}: 'area'"}.join "," %>
        },
      },
      groups: [
        [<%= raw @users.map {|u| "\"#{u}\""}.join "," %>]
      ],
      axis: {
        x: {
          type: 'category' // this needed to load string x value
        },
        y: {
          min: 0,
          padding: { bottom:0 }
        }
      }
    });
  });
</script>

app/views/users/signup_new.html.erb
<div class="col-md-6 col-md-offset-3 white-bg">
  <h1 class="login-title">Pick it up! <span class="title-version">Beta</span></h1>

  <% if flash[:alert] %>
  <p id="notice" class="alert alert-danger"><%= flash[:alert] %></p>
  <% end %>
  
  <% unless @error %>
  <p class="text-info"><i class="fa fa-info"></i> Please, to <strong>sign up</strong> fill in an username and a password.</p>

  <%= form_tag '/signup', role: 'form' do %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <%= label_tag :username, 'Username', class: 'sr-only' %>
      <%= text_field_tag :username, params[:username], class: 'form-control', placeholder: "Username", autocomplete: "off" %>
    </div>
    <div class="form-group">
      <%= label_tag :password, 'Password', class: 'sr-only' %>
      <%= password_field_tag :password, params[:password], class: 'form-control', placeholder: "Password", autocomplete: "off" %>
    </div>
    <div class="form-group">
      <%= label_tag :password_confirmation, 'Password', class: 'sr-only' %>
      <%= password_field_tag :password_confirmation, params[:password_confirmation], class: 'form-control', placeholder: "Password confirmation", autocomplete: "off" %>
    </div>
    <%= hidden_field_tag :email, @user.email %>
    <hr>
    <div class="form-group">
      <%= submit_tag "Sign up", class: 'btn btn-primary login-submit' %>
    </div>
  <% end %>
  <% end %>
</div>