config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :pickups
  put 'pickups/coordinates/:id' => 'pickups#update_coordinates'
  patch 'pickups/coordinates/:id' => 'pickups#update_coordinates'
  resources :users
  
  get 'profile', to: 'users#profile'
  get 'signup', to: 'users#signup_new'
  post 'signup', to: 'users#signup'

  root 'dashboard#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Pick it up!</title>
  <meta name="viewport" content="width=device-width">
  <meta name="theme-color" content="#c3886a">

  <%= favicon_link_tag 'favicon-16x16.png', {type: 'image/png', sizes: '16x16'} %>
  <%= favicon_link_tag 'favicon-32x32.png', {type: 'image/png', sizes: '32x32'} %>
  <%= favicon_link_tag 'favicon-96x96.png', {type: 'image/png', sizes: '96x96'} %>
  <%= favicon_link_tag 'android-icon-144x144.png', {rel: 'icon', type: 'image/png', sizes: '144x144'} %>
  <%= favicon_link_tag 'android-icon-192x192.png', {rel: 'icon', type: 'image/png', sizes: '192x192'} %>
  <%= favicon_link_tag 'android-icon-36x36.png', {rel: 'icon', type: 'image/png', sizes: '36x36'} %>
  <%= favicon_link_tag 'android-icon-48x48.png', {rel: 'icon', type: 'image/png', sizes: '48x48'} %>
  <%= favicon_link_tag 'android-icon-72x72.png', {rel: 'icon', type: 'image/png', sizes: '72x72'} %>
  <%= favicon_link_tag 'android-icon-96x96.png', {rel: 'icon', type: 'image/png', sizes: '96x96'} %>
  <%= favicon_link_tag 'apple-icon-57x57.png', {rel: 'apple-touch-icon', sizes: '57x57'} %>
  <%= favicon_link_tag 'apple-icon-60x60.png', {rel: 'apple-touch-icon', sizes: '60x60'} %>
  <%= favicon_link_tag 'apple-icon-72x72.png', {rel: 'apple-touch-icon', sizes: '72x72'} %>
  <%= favicon_link_tag 'apple-icon-76x76.png', {rel: 'apple-touch-icon', sizes: '76x76'} %>
  <%= favicon_link_tag 'apple-icon-114x114.png', {rel: 'apple-touch-icon', sizes: '114x114'} %>
  <%= favicon_link_tag 'apple-icon-120x120.png', {rel: 'apple-touch-icon', sizes: '120x120'} %>
  <%= favicon_link_tag 'apple-icon-144x144.png', {rel: 'apple-touch-icon', sizes: '144x144'} %>
  <%= favicon_link_tag 'apple-icon-152x152.png', {rel: 'apple-touch-icon', sizes: '152x152'} %>
  <%= favicon_link_tag 'apple-icon-180x180.png', {rel: 'apple-touch-icon', sizes: '180x180'} %>

  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="mobile-web-app-capable" content="yes">

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Open layers -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css" type="text/css">
  <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Pick it up!</a>
      </div>
      <div class="navbar-right">
        <ul class="nav navbar-nav">
          <li class="dropdown">
          <li><%= link_to  profile_path, :title => "Profile" do %><i class="fa fa-user fa-2x"></i><% end %></li>
          <li><%= link_to new_pickup_path, :title => "New pickup" do %><i class="fa fa-plus fa-2x"></i><% end %></li>
        </ul>
      </div>
    </div>
  </nav>

  <section id="main" class="container-fluid">
    <%= yield %>
  </section>

  <footer>
    <div class="container-fluid">
      <span class="credits">Made with <i class="fa fa-heart" style="color: red;"></i> in Murcia and Madrid</span>
    </div>
  </footer>

  <% if Rails.env.production? %>
  <!-- Google analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-47077118-6', 'auto');
    ga('send', 'pageview');
  </script>
  <% end %>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en" <%if @login_page %>class="login"<% end %>>
<head>
  <meta charset="utf-8">
  <title>Pick it up!</title>
  <meta name="viewport" content="width=device-width">
  <meta name="theme-color" content="#c3886a">

  <%= favicon_link_tag 'favicon-16x16.png', {type: 'image/png', sizes: '16x16'} %>
  <%= favicon_link_tag 'favicon-32x32.png', {type: 'image/png', sizes: '32x32'} %>
  <%= favicon_link_tag 'favicon-96x96.png', {type: 'image/png', sizes: '96x96'} %>
  <%= favicon_link_tag 'favicon-192x192.png', {type: 'image/png', sizes: '192x192'} %>
  <%= favicon_link_tag 'android-icon-192x192.png', {rel: 'icon', type: 'image/png', sizes: '192x192'} %>
  <%= favicon_link_tag 'android-icon-32x32.png', {rel: 'icon', type: 'image/png', sizes: '32x32'} %>
  <%= favicon_link_tag 'android-icon-96x96.png', {rel: 'icon', type: 'image/png', sizes: '96x96'} %>
  <%= favicon_link_tag 'android-icon-16x16.png', {rel: 'icon', type: 'image/png', sizes: '16x16'} %>
  <%= favicon_link_tag 'apple-icon-57x57.png', {rel: 'apple-touch-icon', sizes: '57x57'} %>
  <%= favicon_link_tag 'apple-icon-60x60.png', {rel: 'apple-touch-icon', sizes: '60x60'} %>
  <%= favicon_link_tag 'apple-icon-72x72.png', {rel: 'apple-touch-icon', sizes: '72x72'} %>
  <%= favicon_link_tag 'apple-icon-76x76.png', {rel: 'apple-touch-icon', sizes: '76x76'} %>
  <%= favicon_link_tag 'apple-icon-114x114.png', {rel: 'apple-touch-icon', sizes: '114x114'} %>
  <%= favicon_link_tag 'apple-icon-120x120.png', {rel: 'apple-touch-icon', sizes: '120x120'} %>
  <%= favicon_link_tag 'apple-icon-144x144.png', {rel: 'apple-touch-icon', sizes: '144x144'} %>
  <%= favicon_link_tag 'apple-icon-152x152.png', {rel: 'apple-touch-icon', sizes: '152x152'} %>
  <%= favicon_link_tag 'apple-icon-180x180.png', {rel: 'apple-touch-icon', sizes: '180x180'} %>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="mobile-web-app-capable" content="yes">

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="container-fluid vertical-align">
    <%= yield %>
  </section>

  <!-- Google analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-47077118-6', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>